import js from "@eslint/js";
import globals from "globals";
import importPlugin from "eslint-plugin-import";

export default [
    {
        files: ["**/*.{js,mjs,cjs}"],
        plugins: {
            import: importPlugin,
        },
        languageOptions: {
            globals: {
                ...globals.node,
                global: "readonly",
            },
            sourceType: "module",
            ecmaVersion: 2022,
        },
        rules: {
            ...js.configs.recommended.rules,
            ...importPlugin.configs.recommended.rules,
            "import/no-unresolved": "error",
            "import/named": "error",
            "import/default": "error",
            "import/namespace": "error",
            "no-unused-vars": "off",
            "no-undef": "error",
            "no-redeclare": "error",
            "no-shadow": "warn",
            "no-unreachable": "error",
            "no-duplicate-case": "error",
            "no-fallthrough": "error",
            "no-constant-condition": "error",
            "no-unreachable-loop": "error",
            "no-inner-declarations": "error",
            "no-func-assign": "error",
            "getter-return": "error",
            "no-async-promise-executor": "error",
            "no-compare-neg-zero": "error",
            "no-cond-assign": "error",
            "no-dupe-args": "error",
            "no-dupe-keys": "error",
            "no-duplicate-imports": "error",
            "no-implicit-globals": "off",
            strict: "off",
            "no-self-assign": "error",
            "no-self-compare": "error",
            "no-ex-assign": "error",
            "no-global-assign": "error",
            "no-invalid-regexp": "error",
            "no-obj-calls": "error",
            "no-prototype-builtins": "error",
            "no-sparse-arrays": "error",
            "no-unexpected-multiline": "error",
            "use-isnan": "error",
            "valid-typeof": "error",
            indent: "off",
            quotes: "off",
            semi: "off",
            "comma-dangle": "off",
            "space-before-function-paren": "off",
            "object-curly-spacing": "off",
            "no-console": "off",
            "no-debugger": "warn",
            "no-alert": "off",
            "no-var": "off",
            "prefer-const": "off",
        },
    },
];
